---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: velero
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-operator
  namespace: velero
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: velerocontrollers.migration.openshift.io
spec:
  group: migration.openshift.io
  names:
    kind: VeleroController
    listKind: VeleroControllerList
    plural: velerocontrollers
    singular: velerocontroller
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: velero-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mig-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - velero.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: velero-operator
subjects:
- kind: ServiceAccount
  name: velero-operator
roleRef:
  kind: Role
  name: velero-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: velero-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: velero-operator
    namespace: velero
namespace: velero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: velero-operator
  template:
    metadata:
      labels:
        name: velero-operator
    spec:
      serviceAccountName: velero-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: docker.io/jmontleon/velero-operator:v0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: docker.io/jmontleon/velero-operator:v0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "velero-operator"
      volumes:
        - name: runner
          emptyDir: {}
